In [1]:
import tensorflow as tf
import keras

Using TensorFlow backend.


In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
df=pd.read_csv('Churn_Modelling.csv')

In [4]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [5]:
df.shape

(10000, 14)

In [6]:
X=df.iloc[:,3:13].values
y=df.iloc[:,13].values

In [7]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_1=LabelEncoder()
labelencoder_2=LabelEncoder()

In [8]:
X[:,1]=labelencoder_1.fit_transform(X[:,1])
X[:,2]=labelencoder_2.fit_transform(X[:,2])


In [9]:
onehotencoder=OneHotEncoder(categorical_features=[1])

In [10]:
X=onehotencoder.fit_transform(X).toarray()

C:\Users\nanao\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\nanao\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [11]:
X.shape

(10000, 12)

In [12]:
X=X[:,1:]


In [13]:
X.shape

(10000, 11)

In [14]:
X

array([[0.0000000e+00, 0.0000000e+00, 6.1900000e+02, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 1.0000000e+00, 6.0800000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [0.0000000e+00, 0.0000000e+00, 5.0200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [0.0000000e+00, 0.0000000e+00, 7.0900000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [1.0000000e+00, 0.0000000e+00, 7.7200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [0.0000000e+00, 0.0000000e+00, 7.9200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [15]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2, random_state=0)

In [16]:
X_test.shape

(2000, 11)

In [17]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.fit_transform(X_test)

In [18]:
X_train

array([[-0.5698444 ,  1.74309049,  0.16958176, ...,  0.64259497,
        -1.03227043,  1.10643166],
       [ 1.75486502, -0.57369368, -2.30455945, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [-0.5698444 , -0.57369368, -1.19119591, ...,  0.64259497,
        -1.03227043,  1.48533467],
       ...,
       [-0.5698444 , -0.57369368,  0.9015152 , ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-0.5698444 ,  1.74309049, -0.62420521, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [ 1.75486502, -0.57369368, -0.28401079, ...,  0.64259497,
        -1.03227043,  0.32472465]])

In [19]:
## Creatign ANN 

In [20]:
from keras.models import Sequential
from keras.layers import Dense

In [21]:
## initializing the ANN
classifier=Sequential()

In [22]:
## adding the input and hidden layer in the ANN
classifier.add(Dense(6,activation='relu',kernel_initializer='uniform',input_shape=(11,)))

Instructions for updating:
Colocations handled automatically by placer.


In [23]:
classifier.add(Dense(6,activation='relu',kernel_initializer='uniform')) ## adding 2nd hidden layer

In [24]:
classifier.add(Dense(1,activation='sigmoid',kernel_initializer='uniform')) ## adding output layer

In [25]:
classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [26]:
classifier.fit(X_train,y_train,epochs=10,batch_size=1)

Instructions for updating:
Use tf.cast instead.
Epoch 1/10
8000/8000 [==============================] - 17s 2ms/step - loss: 0.4228 - acc: 0.8135: 0s - loss: 0.
Epoch 2/10
8000/8000 [==============================] - 22s 3ms/step - loss: 0.3854 - acc: 0.8306
Epoch 3/10
8000/8000 [==============================] - 17s 2ms/step - loss: 0.3754 - acc: 0.8427
Epoch 4/10
8000/8000 [==============================] - 17s 2ms/step - loss: 0.3696 - acc: 0.8468
Epoch 5/10
8000/8000 [==============================] - 16s 2ms/step - loss: 0.3642 - acc: 0.8482
Epoch 6/10
8000/8000 [==============================] - 15s 2ms/step - loss: 0.3614 - acc: 0.8522
Epoch 7/10
8000/8000 [==============================] - 13s 2ms/step - loss: 0.3597 - acc: 0.8499
Epoch 8/10
8000/8000 [==============================] - 14s 2ms/step - loss: 0.3578 - acc: 0.8518
Epoch 9/10
8000/8000 [==============================] - 11s 1ms/step - loss: 0.3550 - acc: 0.8505
Epoch 10/10
8000/8000 [==============================] 

In [27]:
y_pred=classifier.predict(X_test)

In [28]:
y_pred

array([[0.17905274],
       [0.2857638 ],
       [0.09345028],
       ...,
       [0.15334764],
       [0.11092618],
       [0.16712466]], dtype=float32)